name: lust
description: Library Universal Swiss Tool
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  geolocator: ^4.0.3
  cupertino_icons: ^0.1.2

  flutter:
    sdk: flutter
  cloud_firestore: ^0.11.0+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  charts_flutter: ^0.6.0


flutter:
  uses-material-design: true